name: Generate WakaTime Statistics

on:
  schedule:
    - cron: '44 13 * * *'

jobs:
  generate-statistics:
    name: Update the WakaTime statistics
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
